[package]
name = "contract"
version = "1.0.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { git = "https://github.com/jong-un-crypto/near-sdk-rs", branch = "master" }
uint = { version = "0.9.3", default-features = false }

[dev-dependencies]
borsh = { git = "https://github.com/near/borsh-rs", branch = "master" }

[patch.crates-io]
### parity-secp256k1 = {git = "https://github.com/paritytech/rust-secp256k1"}
### near-vm-logic = { git = "https://github.com/near/nearcore", branch = "master" }
### near-primitives-core = { git = "https://github.com/near/nearcore", branch = "master" }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
members = []
